version: 2.1
jobs:
  build:
    docker:
      - image: instrumentisto/rust:nightly-alpine
    steps:
      - checkout
      - run: apk -UvX http://dl-cdn.alpinelinux.org/alpine/edge/main add -u musl-dev llvm-dev
      - run: cargo fmt --all -- --check
      - run: cargo clippy -- -Dwarnings
