[package]
name = "trippy-compiler"
version = "0.0.1"
edition = "2021"
license = "MIT"

[dependencies]
trippy-compiler-core = { path = "../compiler-core" }
miette = { version = "4.7.1", features = ["fancy"] }
bpaf = "0.4.4"
cranelift = "0.84.0"
cranelift-jit = "0.84.0"
cranelift-object = "0.84.0"
